[workspace]
members = [ "o2-thing-client","o2-thing-server", "upload-things"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.94"
upload-things = { path = "upload-things" }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
